<?php
/**
 * Mainframe Theme — Login URL Customization
 *
 * Implements a custom login URL slug natively in PHP without plugin
 * dependencies. Intercepts requests to the configured slug and routes
 * them to wp-login.php, and blocks direct access to wp-login.php when
 * a custom slug is active.
 *
 * @package Mainframe
 */

defined( 'ABSPATH' ) || exit;

// ---------------------------------------------------------------------------
// Early request interception — must fire before headers are sent.
// ---------------------------------------------------------------------------

add_action( 'init', 'mainframe_handle_login_request', 1 );
/**
 * Intercept requests to the custom login slug and route them to wp-login.php.
 *
 * Runs at priority 1 on 'init' so it fires before any rewrite rules or
 * redirect logic added by the theme or plugins. Does nothing when no slug
 * is configured, leaving WordPress's default behaviour intact.
 *
 * Security considerations:
 * - The slug is sanitized on save (see options.php) so no sanitization is
 *   needed here at read time.
 * - We compare against the raw request URI after stripping the home path so
 *   the check is host-independent.
 * - wp-login.php access is blocked separately below.
 */
function mainframe_handle_login_request(): void {
	$slug = mainframe_get_login_slug();

	if ( empty( $slug ) ) {
		return;
	}

	$request_path = mainframe_get_request_path();

	// Serve wp-login.php for requests matching /<slug> or /<slug>/.
	if ( rtrim( $request_path, '/' ) === '/' . $slug ) {
		// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingCustomFunction
		require_once ABSPATH . 'wp-login.php';
		exit;
	}
}

add_action( 'init', 'mainframe_block_default_login', 1 );
/**
 * Block direct access to wp-login.php when a custom slug is active.
 *
 * When a custom slug is configured, a request to the bare /wp-login.php
 * path should not succeed — it would defeat the purpose of the rename.
 * We redirect such requests to the home page with a 302 rather than
 * returning a 404, to avoid leaking information about the existence of
 * the login system.
 *
 * Requests that carry a valid action parameter and come from wp-admin
 * redirects (e.g. logout, password reset confirmation) are allowed
 * through so core functionality is not broken. WordPress itself always
 * initiates these via the internal wp_login_url() / admin_url() helpers;
 * we filter those to the custom slug via login_url below.
 *
 * Exception: POST requests to wp-login.php are never blocked — plugins
 * and external systems may rely on POSTing credentials directly.
 */
function mainframe_block_default_login(): void {
	$slug = mainframe_get_login_slug();

	if ( empty( $slug ) ) {
		return;
	}

	$request_path = mainframe_get_request_path();

	if ( rtrim( $request_path, '/' ) !== '/wp-login.php' ) {
		return;
	}

	// Allow POST (credential submission) and requests with a recognised
	// action so core password-reset / logout flows are not broken.
	$method = isset( $_SERVER['REQUEST_METHOD'] ) ? strtoupper( sanitize_text_field( wp_unslash( $_SERVER['REQUEST_METHOD'] ) ) ) : 'GET';
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
	$action = isset( $_GET['action'] ) ? sanitize_key( $_GET['action'] ) : '';
	$allowed_actions = [ 'logout', 'lostpassword', 'rp', 'resetpass', 'postpass', 'confirmaction', 'register' ];

	if ( 'POST' === $method || in_array( $action, $allowed_actions, true ) ) {
		return;
	}

	wp_safe_redirect( home_url( '/' ), 302 );
	exit;
}

// ---------------------------------------------------------------------------
// Filter WordPress's login URL helpers to use the custom slug.
// ---------------------------------------------------------------------------

add_filter( 'login_url', 'mainframe_filter_login_url', 10, 3 );
/**
 * Replace wp-login.php in URLs generated by wp_login_url() and login_url().
 *
 * WordPress passes the constructed URL through this filter before returning
 * it to callers. We swap the wp-login.php segment for the custom slug so
 * admin redirects, password-reset emails, and any code using the canonical
 * helper all point to the right place.
 *
 * @param string $login_url    The login URL (already has scheme and host).
 * @param string $redirect     The redirect URL passed to wp_login_url().
 * @param bool   $force_reauth Whether to force reauthorization.
 * @return string Modified login URL.
 */
function mainframe_filter_login_url( string $login_url, string $redirect, bool $force_reauth ): string {
	$slug = mainframe_get_login_slug();

	if ( empty( $slug ) ) {
		return $login_url;
	}

	return str_replace( 'wp-login.php', $slug, $login_url );
}

add_filter( 'logout_url', 'mainframe_filter_logout_url', 10, 2 );
/**
 * Replace wp-login.php in URLs generated by wp_logout_url().
 *
 * @param string $logout_url The logout URL.
 * @param string $redirect   The redirect URL passed to wp_logout_url().
 * @return string Modified logout URL.
 */
function mainframe_filter_logout_url( string $logout_url, string $redirect ): string {
	$slug = mainframe_get_login_slug();

	if ( empty( $slug ) ) {
		return $logout_url;
	}

	return str_replace( 'wp-login.php', $slug, $logout_url );
}

add_filter( 'lostpassword_url', 'mainframe_filter_lostpassword_url', 10, 2 );
/**
 * Replace wp-login.php in lost-password URLs.
 *
 * @param string $lostpassword_url The lost-password URL.
 * @param string $redirect         The redirect URL.
 * @return string Modified lost-password URL.
 */
function mainframe_filter_lostpassword_url( string $lostpassword_url, string $redirect ): string {
	$slug = mainframe_get_login_slug();

	if ( empty( $slug ) ) {
		return $lostpassword_url;
	}

	return str_replace( 'wp-login.php', $slug, $lostpassword_url );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Return the configured login slug, or an empty string if none is set.
 *
 * Uses a static variable to avoid repeated get_option() calls within a
 * single request.
 *
 * @return string
 */
function mainframe_get_login_slug(): string {
	static $slug = null;

	if ( null === $slug ) {
		$slug = (string) get_option( 'mainframe_login_slug', '' );
	}

	return $slug;
}

/**
 * Return the current request path relative to the WordPress home path.
 *
 * Strips the home URL path prefix so the comparison in the hooks above
 * works correctly on WordPress installs in subdirectories.
 *
 * @return string Request path starting with '/', e.g. '/login' or '/wp-login.php'.
 */
function mainframe_get_request_path(): string {
	$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? sanitize_text_field( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '/';
	// Strip query string.
	$path = (string) parse_url( $request_uri, PHP_URL_PATH );

	// Remove the home URL's path prefix for sub-directory installs.
	$home_path = (string) parse_url( home_url(), PHP_URL_PATH );
	if ( $home_path && '/' !== $home_path && str_starts_with( $path, $home_path ) ) {
		$path = substr( $path, strlen( $home_path ) );
	}

	return '/' . ltrim( $path, '/' );
}
